# name: Publish
# on:
#   push:
#     branches: ["main"]

# concurrency: ${{ github.workflow }}-${{ github.ref }}

# jobs:
#   publish:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18.x
#           registry-url: https://registry.npmjs.org/
#           cache: "yarn"
#       - run: yarn install
#       - run: yarn tsc
#       - run: yarn build:all

#       - name: Create Release Pull Request or Publish
#         id: changesets
#         uses: changesets/action@v1
#         with:
#           version: yarn changeset version
#           publish: yarn changeset publish
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

#       - name: Push latest version
#         if: steps.changesets.outputs.published == 'true'
#         run: git push origin main --follow-tags
